{
 "title": "OpenClash",
 "description": "Clash exporter example dashboard",
 "tags": [ "openclash" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, source)"
    }
   },
   {
    "name": "policy",
    "label": "policy",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, policy)"
    }
   },
   {
    "name": "type",
    "label": "type",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clash_network_traffic_bytes_total{source=~\"$source\", policy!=\"DIRECT\", policy=~\"$policy\",type=~\"$type\"})",
     "legendFormat": "国际流量"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clash_network_traffic_bytes_total{source=~\"$source\", policy=\"DIRECT\", policy=~\"$policy\",type=~\"$type\"})",
     "legendFormat": "国内流量"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"download\"}[30s]))",
     "legendFormat": "下载速度"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"upload\"}[1m]))",
     "legendFormat": "上传速度"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_download_bytes_total", "legendFormat": "总下载量" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_upload_bytes_total", "legendFormat": "总上传量" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_active_connections", "legendFormat": "连接数" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(clash_info, \"ClashVersion\", \", \\n is_premium: \", \"version\", \"premium\")",
     "legendFormat": "Clash Version"
    }
   ]
  },
  {
   "title": "代理总流量",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (chain_last) (clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"})",
     "legendFormat": "来源"
    }
   ]
  },
  {
   "title": "代理总流量",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (policy) (clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"})",
     "legendFormat": "来源"
    }
   ]
  },
  {
   "title": "下载速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"download\"}[30s]))",
     "legendFormat": "下载速度"
    }
   ]
  },
  {
   "title": "上传速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"upload\"}[30s]))",
     "legendFormat": "上传速度"
    }
   ]
  },
  {
   "title": "规则组速度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (chain_last)(rate(clash_network_traffic_bytes_total{type=\"download\"}[30s]))",
     "legendFormat": "{{chain_last}} D"
    },
    {
     "expr": "sum by (chain_last) (rate(clash_network_traffic_bytes_total{type=\"upload\"}[30s]))",
     "legendFormat": "{{chain_last}} U"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "options": {
    "content": "<div style=\"display: flex;justify-content: center;align-items: center;overflow: hidden;width:100%;heigt:100%\">\n<img src=\"https://azusebox.moe/wp-content/uploads/2023/06/yande.re-971345-ke-ta-konpaku_youmu-myon-touhou.png\" style=\"object-fit: fill;flex-shrink: 0;min-width: 100%;min-height: 100%;width: auto;\"></img>\n</div>"
   }
  },
  {
   "title": "客户端总流量（排除Direct）",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (source) (clash_network_traffic_bytes_total{source=~\"$source\", policy!=\"DIRECT\", policy=~\"$policy\", type=~\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "目的地总流量（排除Direct）",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (destination) (clash_network_traffic_bytes_total{source=~\"$source\", policy!=\"DIRECT\", policy=~\"$policy\",type=~\"$type\"}))",
     "legendFormat": "来源"
    }
   ]
  },
  {
   "title": "客户端总流量（仅Direct）",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (source) (clash_network_traffic_bytes_total{source=~\"$source\", policy=\"DIRECT\", policy=~\"$policy\", type=~\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "目的地总流量（排除Direct）",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (destination) (clash_network_traffic_bytes_total{source=~\"$source\", policy=\"DIRECT\", policy=~\"$policy\",type=~\"$type\"}))",
     "legendFormat": "来源"
    }
   ]
  },
  {
   "title": "策略流量统计",
   "type": "table",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (chains, destination, source, type) (clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "目的地速度",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (destination)(rate(clash_network_traffic_bytes_total{type=\"download\"}[30s])) != 0",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Traffic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "客户端流量统计",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1h]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[3h]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[6h]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1d]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tracing Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rule Match Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(clash_tracing_rule_match_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_rule_match_duration_milliseconds_count{}[1m]))",
       "legendFormat": "AVG"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_rule_match_duration_milliseconds_bucket{}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Proxy Dial Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(clash_tracing_proxy_dial_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_proxy_dial_duration_milliseconds_count{}[1m]))",
       "legendFormat": "AVG"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_proxy_dial_duration_milliseconds_bucket{}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "DNS Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(clash_tracing_dns_request_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_dns_request_duration_milliseconds_count{}[1m]))",
       "legendFormat": "AVG"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_dns_request_duration_milliseconds_bucket[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    }
   ]
  }
 ]
}